#!/bin/csh
source initpath
# monochromatic calculation

# biomass section
setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_a.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_b.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_c.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_d.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_australia.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_indonesia.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# sulphuric-acid section
setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='sulphuric-acid_300.mm',lutfile='sulphuric-acid-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# volcanic-ash section
setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='volcanic-ash_ctn.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='volcanic-ash_ey1.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

setenv CREATE_ORAC_LUT_DRIVER 'input_files/driver/aqua_modis_cloud.driver'
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='volcanic-ash_spr.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

