#!/bin/bash
source initpath.bash
# monochromatic calculation
# biomass section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/himawari-8_ahi_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_australia_minus.mm',lutfile='biomass-plume+.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=13"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/himawari-8_ahi_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_australia.mm',lutfile='biomass-plume+.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=13"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/himawari-8_ahi_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_australia_plus.mm',lutfile='biomass-plume+.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=13"

