#!/bin/bash
source initpath.bash
# monochromatic calculation
# aerosol section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='aerosol_a70.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='aerosol_a75.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='aerosol_a76.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='aerosol_a77.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='aerosol_a79.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# biomass section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_a.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_b.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_c.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_d.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_australia.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='biomass_indonesia.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# liquid-water section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_stg.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_stg.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_240.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_240.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_253.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_253.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_263.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_263.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_273.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_273.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# sulphuric-acid section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='sulphuric-acid_300.mm',lutfile='sulphuric-acid-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# volcanic-ash section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='volcanic-ash_ctn.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='volcanic-ash_ey1.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='volcanic-ash_spr.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# water-ice section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_sph.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_agg.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_ghm.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_src.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# band  calculation
# aerosol section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='aerosol_a70.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='aerosol_a75.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='aerosol_a76.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='aerosol_a77.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_aerosol.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='aerosol_a79.mm',lutfile='aerosol.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# biomass section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='biomass_a.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='biomass_b.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='biomass_c.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='biomass_d.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='biomass_australia.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='biomass_indonesia.mm',lutfile='biomass-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# liquid-water section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_stg.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_stg.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_240.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_240.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_253.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_253.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_263.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_263.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_273.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='liquid-water_273.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# sulphuric-acid section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='sulphuric-acid_300.mm',lutfile='sulphuric-acid-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# volcanic-ash section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='volcanic-ash_ctn.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='volcanic-ash_ey1.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='volcanic-ash_spr.mm',lutfile='ash-plume.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# water-ice section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='water-ice_sph.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='water-ice_agg.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='water-ice_ghm.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/meteosat-9_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=2,mmfile='water-ice_src.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

