#!/bin/bash
#*** WARN USER THAT THIS IS A TEST RUN ***
echo
echo
echo
echo "****************************************"
echo "*** TEST TEST TEST TEST TEST TEST ***"
echo "*** THIS IS A TEST LUT GENERATION  ***"
echo "****************************************"
echo
echo
echo
source setup_oraclut_env.sh
echo
echo
# monochromatic calculation
# aerosol section
export CREATE_ORAC_AEROSOL_LUT_DRIVER="input_files/driver/sentinel-3a_slstr_aerosol.driver"
echo "using ..." $CREATE_ORAC_AEROSOL_LUT_DRIVER
idl -e "create_orac_aerosol_lut_wrapper,srf_quad=1,mmfile='aerosol_a70.mm',lutfile='aerosol_test.lut',tmatrix_path='/network/aopp/matin/eodg/shared/dubovik_tmatrix/',atmospheres=2,gas=1,version=21"

# water-ice section
export CREATE_ORAC_CLOUD_LUT_DRIVER="input_files/driver/sentinel-3a_slstr_cloud.driver"
echo "using ..." $CREATE_ORAC_CLOUD_LUT_DRIVER
idl -e "create_orac_cloud_lut_wrapper,srf_quad=1,mmfile='water-ice_sph.mm',lutfile='ice-cloud_test.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=21"

