#!/bin/bash
source initpath4.bash
#*** TEST RUN ***
# monochromatic calculation
# liquid-water section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/envisat_aatsr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud_test.lut',version=51,/reuse_scat"

