#!/bin/bash
source initpath.bash
module load intel-compilers/2022
#*** TEST RUN ***
# band  calculation
# liquid-water section
export CREATE_ORAC_CLOUD_LUT_DRIVER="input_files/driver/meteosat-10_seviri_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_cloud_lut_wrapper,srf_quad=2,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud_test.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=21, channelid=[1,10]"

