#!/bin/bash
source initpath.bash
# monochromatic calculation
# liquid-water section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_old.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_stg.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_stg.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_240.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_240.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_253.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_253.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_263.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_263.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_273.mm',lutfile='liquid-water-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='liquid-water_273.mm',lutfile='liquid-water-cloud.lut',no_rayleigh=1,reuse_scat=1,tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

# water-ice section
export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_sph.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_agg.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_ghm.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

export CREATE_ORAC_LUT_DRIVER="input_files/driver/noaa-6_avhrr_cloud.driver"
echo "making ..." $CREATE_ORAC_LUT_DRIVER
idl -e "create_orac_lut_wrapper,srf_quad=1,mmfile='water-ice_src.mm',lutfile='ice-cloud.lut',tmatrix_path='/network/group/aopp/eodg/shared/dubovik_tmatrix/',version=11"

