"""Compare LUTs regenerated by the recovered V22 generator with the archived V22 and IDL V21 products.

    python validation/v22_recovery/compare_regenerated.py REGEN_ROOT [--cases ID,ID,...]

For every campaign case listed in the archived campaign summary
(``docs/validation_history/python_v22/campaign_summary.json`` of the
2026-09-29 backup tree) that has a regenerated product under
``REGEN_ROOT/case<ID>/``, the script compares, variable by variable and with
auto-masking disabled:

- regenerated versus archived Python V22 product: bitwise identity per variable;
- regenerated versus IDL V21 product: maximum absolute and relative differences,
  reported next to the archived-V22-versus-V21 values so that the two agree
  exactly when the regenerated product is the archived one;
- the V22 freeze envelopes (validation_history/python_v22/V22_FREEZE.md):
  metadata 0.0400390625, particle optics 0.0088958740234375, RT operators
  0.0008418560028076172, applied as in the original campaign.

Read-only on every archive; writes ``results_regenerated_vs_archives.md`` and
``.tsv`` next to this script.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
from netCDF4 import Dataset

HERE = Path(__file__).resolve().parent
BACKUP = Path("/network/scratch/grainger/quota-relief/project-oraclut-bloated-backup")
SUMMARY = BACKUP / "docs/validation_history/python_v22/campaign_summary.json"
METADATA = {"central_wavelength", "central_wavenumber", "oldwvn", "oldb1", "oldb2", "oldt1", "oldt2", "F0", "oldf0",
            "oldf1", "snr", "oldnefr", "refbt", "nedt", "oldnebt", "rgu", "rou", "rua", "rub", "ruc"}
OPTICS = {"average_volume_per_particle", "extinction_coefficient", "extinction_coefficient_ratio",
          "single_scatter_albedo", "asymmetry_parameter"}
OPERATORS = {"T_dv", "T_dd", "R_dv", "R_dd", "R_0v", "R_0d", "T_0d", "T_00", "E_md"}
ENVELOPE = {"metadata": 0.0400390625, "optics": 0.0088958740234375, "operators": 0.0008418560028076172}


def family(name: str) -> str:
    if name in OPERATORS:
        return "operators"
    if name in OPTICS:
        return "optics"
    if name in METADATA:
        return "metadata"
    return "other"


def read_all(path: Path) -> dict[str, np.ndarray]:
    out = {}
    with Dataset(path) as ds:
        for name, variable in ds.variables.items():
            variable.set_auto_maskandscale(False)
            if variable.dtype.kind == "S":
                variable.set_auto_chartostring(False)
            out[name] = np.asarray(variable[...])
    return out


def compare(a: dict, b: dict) -> dict:
    """Per-variable identity and maximum differences of ``a`` relative to ``b``."""

    result = {"same_variables": list(a) == list(b), "bitwise": 0, "variables": len(a), "worst": {}}
    for name, x in a.items():
        y = b.get(name)
        if y is None or x.shape != y.shape or x.dtype != y.dtype:
            result["worst"][name] = ("structure", None, None)
            continue
        if x.tobytes() == y.tobytes():
            result["bitwise"] += 1
            continue
        if x.dtype.kind not in "fiu":
            result["worst"][name] = ("text", None, None)
            continue
        xf, yf = x.astype(np.float64), y.astype(np.float64)
        finite = np.isfinite(xf) & np.isfinite(yf)
        if not np.array_equal(np.isfinite(xf), np.isfinite(yf)):
            result["worst"][name] = ("non-finite pattern", None, None)
            continue
        d = np.abs(xf - yf)[finite]
        floor = max(1e-6 * np.max(np.abs(yf[finite])) if finite.any() else 0.0, np.finfo(np.float64).tiny)
        rel = d / np.maximum(np.abs(yf[finite]), floor)
        result["worst"][name] = (family(name), float(d.max()) if d.size else 0.0, float(rel.max()) if rel.size else 0.0)
    return result


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("regen_root", type=Path)
    parser.add_argument("--cases", default=None, help="comma-separated case ids (default: all regenerated)")
    parser.add_argument("--summary", type=Path, default=SUMMARY)
    args = parser.parse_args(argv)

    cases = {c["case_id"]: c for c in json.loads(args.summary.read_text())["cases"]}
    wanted = args.cases.split(",") if args.cases else sorted(p.name[4:] for p in args.regen_root.glob("case*") if p.is_dir())
    rows = []
    lines = ["# Recovered V22 generator (9d663e9) against the archived V22 and IDL V21 campaign products", "",
             f"Regenerated products: `{args.regen_root}`.  Archives: `{BACKUP}` (read-only).", "",
             "| case | instrument | model | qm | regen vs archived V22 | regen vs IDL V21: worst abs (family) | archived V22 vs IDL V21: worst abs | envelopes | ",
             "|---|---|---|---|---|---|---|---|"]
    all_bitwise = True
    for case_id in wanted:
        case = cases[case_id]
        regen_dir = args.regen_root / f"case{case_id}"
        regen = next(iter(regen_dir.glob("*.nc")), None)
        archived = BACKUP / case["python_path"]
        idl = BACKUP / case["idl_path"]
        if regen is None or not archived.exists() or not idl.exists():
            rows.append((case_id, "missing", "", "", "", ""))
            lines.append(f"| {case_id} | {case['instrument']} | | | missing product | | | |")
            continue
        r, a, i = read_all(regen), read_all(archived), read_all(idl)
        ra = compare(r, a)
        ri = compare(r, i)
        ai = compare(a, i)
        bitwise = ra["same_variables"] and ra["bitwise"] == ra["variables"]
        all_bitwise &= bitwise
        worst_ri = {}
        worst_ai = {}
        for name, (fam, absd, rel) in ri["worst"].items():
            if absd is not None:
                worst_ri[fam] = max(worst_ri.get(fam, 0.0), absd)
        for name, (fam, absd, rel) in ai["worst"].items():
            if absd is not None:
                worst_ai[fam] = max(worst_ai.get(fam, 0.0), absd)
        within = all(worst_ri.get(fam, 0.0) <= limit for fam, limit in ENVELOPE.items())
        same_as_archive = all(abs(worst_ri.get(f, 0.0) - worst_ai.get(f, 0.0)) == 0.0 for f in ENVELOPE)
        ri_text = ", ".join(f"{worst_ri.get(f, 0.0):.3g} ({f})" for f in ("metadata", "optics", "operators"))
        ai_text = ", ".join(f"{worst_ai.get(f, 0.0):.3g}" for f in ("metadata", "optics", "operators"))
        rows.append((case_id, case["instrument"], case["forward_model"], case["qm"],
                     f"{ra['bitwise']}/{ra['variables']} bitwise", ri_text, ai_text, within, same_as_archive))
        lines.append(f"| {case_id} | {case['instrument']} | {case['forward_model']} {case['microphysics']} | {case['qm']} | "
                     f"{'IDENTICAL' if bitwise else 'DIFFERS'} ({ra['bitwise']}/{ra['variables']} variables bitwise) | "
                     f"{ri_text} | {ai_text} | {'within' if within else 'EXCEEDED'}; "
                     f"{'same as archive' if same_as_archive else 'differs from archive'} |")
    lines += ["", f"All regenerated products bitwise identical to the archived V22 products: **{all_bitwise}**.",
              "", "Envelopes: metadata 0.0400390625, optics 0.0088958740234375, operators 0.0008418560028076172 "
              "(V22_FREEZE.md).  'other' variables (channel ids, flags, grids, strings) are compared for identity only."]
    (HERE / "results_regenerated_vs_archives.md").write_text("\n".join(lines) + "\n")
    with open(HERE / "results_regenerated_vs_archives.tsv", "w") as handle:
        handle.write("case\tinstrument\tmodel\tqm\tregen_vs_archived_v22\tregen_vs_idl_v21_worst_abs\t"
                     "archived_v22_vs_idl_v21_worst_abs\twithin_envelopes\tsame_as_archive\n")
        for row in rows:
            handle.write("\t".join(str(x) for x in row) + "\n")
    print("\n".join(lines))
    return 0 if all_bitwise else 1


if __name__ == "__main__":
    sys.exit(main())
