"""Validate the V22 Terra MODIS cloud LUTs (read-only on every product).

    python validation/v22_terra_modis/validate_products.py

For each product listed in production_submissions.tsv:

1. readability and structure: the NetCDF opens, the V2 reader accepts it,
   dimensions match the run file's grid and the 36 Terra MODIS channels;
2. coordinates: every axis equals the grid the production loader resolves
   from the run file's LUT definition (exact float32 equality);
3. channels: channel_id is 1..36 and the solar/thermal flags match the
   instrument file;
4. physical content: every operator and optical property is finite; the
   number of values outside the stored valid_range is reported per variable;
5. NC_STRING: every text attribute is NC_STRING and ORAC's nc_get_att_string
   read of the axis spacing attributes succeeds;
6. provenance: the sidecar exists, verifies against the repository
   (commit present, product SHA-256 matches), names lut_version 22 and
   lut-code-v22.1, and its run-file SHA-256 equals the committed run file;
7. cross-check with the V23 product of the same model: V23 was generated by
   the same scientific code (9d663e9 = lut-code-v22) on Grid B, so at the
   grid nodes both grids share the values must agree; the maximum absolute
   and relative differences are reported per variable.

There is no IDL V21 Terra MODIS product for these models (the V21/V22
campaign's Terra MODIS cases are compact liquid-water stg products), so no
V21 comparison is possible; this is reported.

Writes results_validation.md next to this script and exits 1 on any failure.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

import numpy as np
from netCDF4 import Dataset

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT)); sys.path.insert(0, str(ROOT / "src"))
import create_orac_luts as c                                            # noqa: E402
from oraclut.idl_mirror import load_inststr, load_lutstr               # noqa: E402
from oraclut.io import netcdf_c as nc                                   # noqa: E402
from oraclut.io.lut import read_lut                                     # noqa: E402
from oraclut.io.string_attributes import audit_file                     # noqa: E402
from oraclut.provenance import provenance_path, read_provenance         # noqa: E402
from oraclut.version import sha256_file, verify_provenance              # noqa: E402

AXES = {"optical_depth": "opd", "effective_radius": "efr", "solar_zenith": "soz",
        "satellite_zenith": "saz", "relative_azimuth": "raa"}
OPERATORS = ("T_dv", "T_dd", "R_dv", "R_dd", "R_0v", "R_0d", "T_0d", "T_00", "E_md")
OPTICS = ("extinction_coefficient", "extinction_coefficient_ratio", "single_scatter_albedo", "asymmetry_parameter")


def common_index(a: np.ndarray, b: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Indices into a and b of values present in both (float32 exact match after rounding to 1e-4)."""

    ra, rb = np.round(a.astype(np.float64), 4), np.round(b.astype(np.float64), 4)
    shared = np.intersect1d(ra, rb)
    return (np.array([int(np.where(ra == v)[0][0]) for v in shared]),
            np.array([int(np.where(rb == v)[0][0]) for v in shared]))


def cross_check(v22: Path, v23: Path) -> tuple[list[str], dict]:
    lines, worst = [], {}
    with Dataset(v22) as a, Dataset(v23) as b:
        idx = {}
        for axis in AXES:
            ia, ib = common_index(np.asarray(a.variables[axis][:]), np.asarray(b.variables[axis][:]))
            idx[axis] = (ia, ib)
            lines.append(f"  shared {axis}: {len(ia)} values {np.round(np.asarray(a.variables[axis][:])[ia], 4).tolist()}")
        for name in OPERATORS + OPTICS + ("channel_id", "central_wavelength"):
            if name not in a.variables or name not in b.variables:
                continue
            va, vb = a.variables[name], b.variables[name]
            va.set_auto_maskandscale(False); vb.set_auto_maskandscale(False)
            dims = va.dimensions
            if dims != vb.dimensions:
                lines.append(f"  {name}: dimensions differ {dims} vs {vb.dimensions}")
                continue
            sel_a = tuple(idx[d][0] if d in idx else slice(None) for d in dims)
            sel_b = tuple(idx[d][1] if d in idx else slice(None) for d in dims)
            xa = np.asarray(va[:])[np.ix_(*[s if isinstance(s, np.ndarray) else np.arange(va.shape[k]) for k, s in enumerate(sel_a)])]
            xb = np.asarray(vb[:])[np.ix_(*[s if isinstance(s, np.ndarray) else np.arange(vb.shape[k]) for k, s in enumerate(sel_b)])]
            if xa.shape != xb.shape:
                lines.append(f"  {name}: shared-node shapes differ {xa.shape} vs {xb.shape}")
                continue
            d = np.abs(xa.astype(np.float64) - xb.astype(np.float64))
            floor = max(1e-6 * float(np.max(np.abs(xb))) if xb.size else 0.0, np.finfo(np.float64).tiny)
            rel = d / np.maximum(np.abs(xb.astype(np.float64)), floor)
            bitwise = xa.tobytes() == xb.tobytes()
            worst[name] = (float(d.max()) if d.size else 0.0, float(rel.max()) if rel.size else 0.0, bitwise, xa.size)
            lines.append(f"  {name:<30} nodes {xa.size:>9}  {'BITWISE' if bitwise else 'differs'}  max|d| {worst[name][0]:.3g}  max rel {worst[name][1]:.3g}")
    return lines, worst


def validate(row: dict) -> tuple[bool, list[str]]:
    product = Path(row["product"])
    run = ROOT / row["run_file"]
    out = [f"## {product.name}", "", f"SLURM job {row['job_id']} ({row['job_name']}); run file `{row['run_file']}`; "
           f"submitted from revision `{row['revision'][:7]}`.", "", "```"]
    ok = True

    def check(condition: bool, text: str) -> None:
        nonlocal ok
        ok &= bool(condition)
        out.append(("PASS  " if condition else "FAIL  ") + text)

    if not product.exists():
        out += ["FAIL  product missing", "```", ""]
        return False, out
    settings = c.read_runfile(run)
    in_path = ROOT / settings["in_path"]
    inst = load_inststr(in_path / "inst" / settings["instfile"])
    lut = load_lutstr(in_path / "lut" / settings["lutfile"], inst.max_sat_zenith)

    lutfile = read_lut(product)
    check(True, f"opens; V2 reader accepts it; format {lutfile.file_format}; size {product.stat().st_size} bytes")
    dims = dict(lutfile.dimensions)
    expected = {"optical_depth": lut.opd_n, "effective_radius": lut.efr_n, "solar_zenith": lut.soz_n,
                "satellite_zenith": lut.saz_n, "relative_azimuth": lut.raa_n, "channels": 36}
    check(all(dims.get(k) == v for k, v in expected.items()), f"dimensions {{{', '.join(f'{k}: {dims.get(k)}' for k in expected)}}}")
    with Dataset(product) as ds:
        for axis, key in AXES.items():
            values = np.asarray(ds.variables[axis][:])
            check(np.array_equal(values, np.asarray(getattr(lut, key), dtype=np.float32)),
                  f"{axis} equals {settings['lutfile']} ({values.size} values, {values.min():g}..{values.max():g})")
        ids = np.asarray(ds.variables["channel_id"][:])
        check(ids.tolist() == list(range(1, 37)), f"channel_id 1..36 ({ids.size} channels)")
        for flag, attr in (("solar_channel_flag", "solar_channel_flag"), ("thermal_channel_flag", "thermal_channel_flag")):
            check(np.array_equal(np.asarray(ds.variables[flag][:]), np.asarray(getattr(inst, attr))), f"{flag} matches the instrument file")
        out.append(f"      solar channels {int(np.sum(ds.variables['solar_channel_flag'][:]))}, "
                   f"thermal {int(np.sum(ds.variables['thermal_channel_flag'][:]))}, mixed "
                   f"{int(np.sum(ds.variables['mixed_channel_flag'][:]))}")
        for name in OPERATORS + OPTICS:
            if name not in ds.variables:
                continue
            v = ds.variables[name]
            v.set_auto_maskandscale(False)
            x = np.asarray(v[:])
            finite = bool(np.all(np.isfinite(x)))
            vr = np.asarray(getattr(v, "valid_range", [-np.inf, np.inf]), dtype=np.float64)
            outside = int(np.sum((x < vr[0]) | (x > vr[1])))
            check(finite, f"{name:<30} finite; range {x.min():.4g}..{x.max():.4g}; outside valid_range "
                          f"{vr.tolist()}: {outside} of {x.size}")
    audit = audit_file(product)
    reads = {axis: nc.read_string_attribute_like_orac(product, axis, "spacing") for axis in AXES}
    check(audit.compliant, f"NC_STRING contract: {audit.text_attribute_types}; ORAC spacing reads {reads}")

    sidecar = provenance_path(product)
    check(sidecar.exists(), f"provenance sidecar {sidecar.name}")
    if sidecar.exists():
        rec = read_provenance(sidecar)
        ver = verify_provenance(sidecar, lut_path=product, root=ROOT)
        git = rec["source"]["git"]
        check(rec["lut_version"] == 22 and rec["source"]["code_release"] == "lut-code-v22.1",
              f"provenance lut_version {rec['lut_version']}, code_release {rec['source']['code_release']}, "
              f"scientific_config {rec['source']['scientific_config']}")
        check(git["commit"] == row["revision"], f"provenance commit {git['commit']} equals the submitted revision")
        check(ver["commit_in_repository"] and ver.get("lut_sha256_matches"), "commit in repository; product SHA-256 matches")
        check(rec["configuration_file"]["sha256"] == sha256_file(run), "run-file SHA-256 equals the committed run file")
        check(rec["numerics"]["nmom"] == 1000 and rec["radiative_transfer"]["nstreams"] == 60,
              f"numerics: {rec['numerics']['legendre_expansion']}; {rec['numerics']['size_distribution_integration'][:60]}...; "
              f"DISORT {rec['radiative_transfer']['nstreams']} streams; {rec['radiative_transfer']['cloud_emission']}")
        out.append(f"      working tree at generation: {git['working_tree']}; tracked changes {git['tracked_changes']}; "
                   f"generated {rec['generated_utc']} on {rec['source']['software']['hostname']}")
    out.append("```")

    v23 = product.with_name(product.name.replace("_v22.nc", "_v23.nc"))
    out += ["", f"Cross-check with `{v23.name}` (same scientific code, Grid B) at shared nodes:", "", "```"]
    if v23.exists():
        lines, worst = cross_check(product, v23)
        out += lines
        ops = {k: w for k, w in worst.items() if k in OPERATORS}
        bitwise = all(w[2] for w in worst.values())
        out.append(f"  summary: {'all shared values bitwise identical' if bitwise else 'max operator |d| ' + format(max(w[0] for w in ops.values()), '.3g')}")
    else:
        out.append("  V23 product not found")
    out += ["```", "", "IDL V21 reference: none exists for Terra MODIS with this model (the V21/V22 campaign's Terra "
            "MODIS cases are compact liquid-water stg products); no V21 comparison is possible.", ""]
    return ok, out


def main() -> int:
    rows = list(csv.DictReader(open(HERE / "production_submissions.tsv"), delimiter="\t"))
    report = ["# V22 Terra MODIS cloud LUT validation", ""]
    all_ok = True
    for row in rows:
        ok, lines = validate(row)
        all_ok &= ok
        report += lines
    report.append(f"Overall: {'PASS' if all_ok else 'FAIL'}")
    (HERE / "results_validation.md").write_text("\n".join(report) + "\n")
    print("\n".join(report))
    return 0 if all_ok else 1


if __name__ == "__main__":
    sys.exit(main())
